// <auto-generated />
namespace TANAPa_ePlan.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_002));
        
        string IMigrationMetadata.Id
        {
            get { return "201512012200588_002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
